general.import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[window]
opacity = 0.9

[cursor]
style = "Block"
smooth_motion = true
smooth_motion_factor = 0.8
smooth_motion_spring = 0.6
smooth_motion_max_stretch_x = 3.0
smooth_motion_max_stretch_y = 3.0







